@extends('layouts.admin')
@section('title','Detail Permohonan Surat')
@section('content')
<div class="row"><div class="col-md-8"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">{{ $application->application_number }}</h3><span class="label {{ $application->status->badgeClass() }} pull-right">{{ $application->status->label() }}</span></div><div class="box-body">
<h4>Identitas Pemohon</h4><dl class="dl-horizontal"><dt>Nama</dt><dd>{{ $application->applicant_name }}</dd><dt>NIK</dt><dd>{{ $application->maskedNik() }}</dd><dt>WhatsApp</dt><dd>{{ $application->applicant_phone }}</dd><dt>Tempat/Tanggal lahir</dt><dd>{{ $application->birth_place }} {{ $application->birth_date?->format('d-m-Y') }}</dd><dt>Alamat</dt><dd>{{ $application->address }}, Dusun {{ $application->hamlet }}, RT {{ $application->rt }}/RW {{ $application->rw }}</dd><dt>Keperluan</dt><dd>{{ $application->purpose }}</dd></dl>
@if($application->form_data_json)<h4>Data Tambahan</h4><dl class="dl-horizontal">@foreach($application->form_data_json as $key=>$value)<dt>{{ str($key)->replace('_',' ')->title() }}</dt><dd>{{ $value }}</dd>@endforeach</dl>@endif
<hr><h4>Dokumen Persyaratan</h4><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Dokumen</th><th>Nama File</th><th>Ukuran</th><th>Status</th><th></th></tr></thead><tbody>@forelse($application->documents as $document)<tr><td>{{ $document->label }}</td><td>{{ $document->original_name }}</td><td>{{ number_format($document->file_size / 1024, 0) }} KB</td><td><span class="label {{ $document->review_status === 'approved' ? 'label-success' : ($document->review_status === 'rejected' ? 'label-danger' : 'label-warning') }}">{{ ucfirst($document->review_status) }}</span></td><td><a class="btn btn-xs btn-default" href="{{ route('admin.letter-applications.document', [$application, $document->id]) }}"><i class="fa fa-download"></i> Lihat / Unduh</a></td></tr>@empty<tr><td colspan="5" class="text-muted">Belum ada dokumen diunggah.</td></tr>@endforelse</tbody></table></div>
<hr><h4>Riwayat Status</h4><ul class="timeline">@foreach($application->statusHistories->reverse() as $history)<li><i class="fa fa-history bg-blue"></i><div class="timeline-item"><span class="time"><i class="fa fa-clock-o"></i> {{ $history->created_at->timezone('Asia/Jakarta')->format('d/m/Y H:i') }}</span><h3 class="timeline-header">{{ $history->to_status->label() }}</h3><div class="timeline-body">@if($history->public_note)<p><strong>Catatan publik:</strong> {{ $history->public_note }}</p>@endif @if($history->internal_note)<p><strong>Catatan internal:</strong> {{ $history->internal_note }}</p>@endif</div></div></li>@endforeach</ul>
</div></div></div><div class="col-md-4">
<div class="box box-warning"><div class="box-header"><h3 class="box-title">Ubah Status</h3></div><div class="box-body">@if($application->status->allowedTransitions())<form method="post" action="{{ route('admin.letter-applications.status.update',$application) }}">@csrf @method('PATCH')<div class="form-group"><label>Status berikutnya</label><select class="form-control" name="status" required>@foreach($application->status->allowedTransitions() as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div><div class="form-group"><label>Catatan untuk warga</label><textarea class="form-control" name="public_note" rows="3">{{ old('public_note',$application->public_note) }}</textarea></div><div class="form-group"><label>Catatan internal</label><textarea class="form-control" name="internal_note" rows="3">{{ old('internal_note',$application->internal_note) }}</textarea></div><button class="btn btn-warning btn-block">Perbarui Status</button></form>@else<p>Status ini sudah final.</p>@endif</div></div>
<div class="box box-success"><div class="box-header"><h3 class="box-title">WhatsApp Pemohon</h3></div><div class="box-body"><form method="post" action="{{ route('admin.letter-applications.whatsapp.open',$application) }}">@csrf<button class="btn btn-success btn-block"><i class="fa fa-whatsapp"></i> Buka WhatsApp Pemohon</button></form><p class="help-block">WhatsApp hanya dibuka dengan pesan siap kirim. Pastikan Anda menekan Kirim.</p></div></div>
<div class="box"><div class="box-header"><h3 class="box-title">Data Penduduk</h3></div><div class="box-body"><form method="post" action="{{ route('admin.letter-applications.resident.link',$application) }}">@csrf @method('PATCH')<select class="form-control" name="resident_id"><option value="">Tidak dihubungkan</option>@foreach($residents as $resident)<option value="{{ $resident->id }}" @selected($application->resident_id===$resident->id)>{{ $resident->name }} — {{ substr($resident->nik,0,4) }}********{{ substr($resident->nik,-4) }}</option>@endforeach</select><button class="btn btn-default btn-block" style="margin-top:10px">Simpan Keterhubungan</button></form></div></div>
</div></div>
@endsection
