@extends('layouts.admin')
@section('title','Detail Permohonan Surat')
@section('content')
<div class="row"><div class="col-md-8"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">{{ $application->application_number }}</h3><span class="label {{ $application->status->badgeClass() }} pull-right">{{ $application->status->label() }}</span></div><div class="box-body">
<h4>Identitas Pemohon</h4><dl class="dl-horizontal"><dt>Nama</dt><dd>{{ $application->applicant_name }}</dd><dt>NIK</dt><dd>{{ $application->maskedNik() }}</dd><dt>WhatsApp</dt><dd>{{ $application->applicant_phone }}</dd><dt>Alamat</dt><dd>{{ $application->address }}, Dusun {{ $application->hamlet }}, RT {{ $application->rt }}/RW {{ $application->rw }}</dd><dt>Keperluan</dt><dd>{{ $application->purpose }}</dd></dl>
<hr><h4>Dokumen Persyaratan</h4><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Persyaratan</th><th>File</th><th>Status / Review</th></tr></thead><tbody>
@forelse($application->documents as $document)<tr><td>{{ $document->label }}</td><td><a href="{{ route('admin.letter-applications.document',[$application,$document->id]) }}">{{ $document->original_name }}</a><br><small>{{ number_format(($document->size_bytes ?: $document->file_size)/1024,0) }} KB</small></td><td><span class="label label-{{ $document->review_status==='approved'?'success':($document->review_status==='rejected'?'danger':'warning') }}">{{ $document->review_status }}</span><form method="post" action="{{ route('admin.letter-applications.document.review',[$application,$document->id]) }}" style="margin-top:7px">@csrf @method('PATCH')<select name="review_status" class="input-sm"><option value="approved">Sesuai</option><option value="rejected">Minta Diganti</option></select><input name="review_note" class="form-control input-sm" placeholder="Catatan jika ditolak"><button class="btn btn-xs btn-success" style="margin-top:4px">Simpan Review</button></form></td></tr>@empty<tr><td colspan="3">Belum ada dokumen.</td></tr>@endforelse
</tbody></table></div>
<hr><h4>Riwayat Status</h4><ul class="timeline">@foreach($application->statusHistories->reverse() as $history)<li><i class="fa fa-history bg-blue"></i><div class="timeline-item"><span class="time">{{ $history->created_at->format('d/m/Y H:i') }}</span><h3 class="timeline-header">{{ $history->to_status->label() }}</h3></div></li>@endforeach</ul>
</div></div></div><div class="col-md-4"><div class="box box-warning"><div class="box-header"><h3 class="box-title">Ubah Status</h3></div><div class="box-body">@if($application->status->allowedTransitions())<form method="post" action="{{ route('admin.letter-applications.status.update',$application) }}">@csrf @method('PATCH')<select class="form-control" name="status" required>@foreach($application->status->allowedTransitions() as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select><button class="btn btn-warning btn-block" style="margin-top:10px">Perbarui Status</button></form>@else<p>Status ini sudah final.</p>@endif</div></div></div></div>
@endsection
