<?php

use App\Models\{Gallery, GalleryItem, IdmScore, MapFeature, MapLayer, Media, News, NewsCategory, Official, Publication, PublicationAttachment, Redirect, Setting, StatisticDataset, StatisticValue, VillageProfileSection};

return ['resources' => [
    'news' => ['model'=>News::class,'title'=>'Berita','ability'=>'manage-content','search'=>['title','slug','excerpt'],'columns'=>['title'=>'Judul','status'=>'Status','published_at'=>'Terbit'],'fields'=>[
        'category_id'=>['label'=>'Kategori','type'=>'relation','model'=>NewsCategory::class,'display'=>'name','rules'=>'required|exists:news_categories,id'], 'title'=>['label'=>'Judul','rules'=>'required|string|min:5|max:255'],
        'slug'=>['label'=>'Slug','rules'=>'nullable|string|max:255|unique:news,slug,{id}'], 'excerpt'=>['label'=>'Ringkasan','type'=>'textarea','rules'=>'nullable|string|max:1000'], 'content'=>['label'=>'Isi berita','type'=>'editor','rules'=>'required|string|max:100000'],
        'featured_image_id'=>['label'=>'Gambar utama','type'=>'image','relation'=>'featuredImage','media_category'=>'news','rules'=>'nullable|exists:media,id'], 'status'=>['label'=>'Status','type'=>'select','options'=>['draft'=>'Draf','published'=>'Terbit','archived'=>'Arsip'],'rules'=>'required|in:draft,published,archived'],
        'published_at'=>['label'=>'Waktu terbit','type'=>'datetime-local','rules'=>'nullable|date'], 'seo_title'=>['label'=>'Judul SEO','rules'=>'nullable|string|max:255'], 'seo_description'=>['label'=>'Deskripsi SEO','type'=>'textarea','rules'=>'nullable|string|max:320'],
    ]],
    'categories' => ['model'=>NewsCategory::class,'title'=>'Kategori Berita','ability'=>'manage-content','search'=>['name','slug'],'columns'=>['name'=>'Nama','slug'=>'Slug'],'fields'=>['name'=>['label'=>'Nama','rules'=>'required|string|max:100|unique:news_categories,name,{id}'],'slug'=>['label'=>'Slug','rules'=>'nullable|string|max:160|unique:news_categories,slug,{id}'],'description'=>['label'=>'Deskripsi','type'=>'textarea','rules'=>'nullable|string|max:2000']]],
    'publications' => ['model'=>Publication::class,'title'=>'Informasi Publik','ability'=>'manage-content','search'=>['title','type','slug'],'columns'=>['title'=>'Judul','type'=>'Jenis','status'=>'Status','published_at'=>'Terbit'],'fields'=>[
        'type'=>['label'=>'Jenis','type'=>'select','options'=>['announcement'=>'Pengumuman','agenda'=>'Agenda','document'=>'Dokumen'],'rules'=>'required|in:announcement,agenda,document'], 'title'=>['label'=>'Judul','rules'=>'required|string|max:255'], 'slug'=>['label'=>'Slug','rules'=>'nullable|string|max:255|unique:publications,slug,{id}'],
        'excerpt'=>['label'=>'Ringkasan','type'=>'textarea','rules'=>'nullable|string|max:1000'], 'content'=>['label'=>'Isi publikasi','type'=>'editor','rules'=>'required|string|max:100000'], 'featured_image_id'=>['label'=>'Gambar utama','type'=>'image','relation'=>'featuredImage','media_category'=>'banners','rules'=>'nullable|exists:media,id'],
        'start_date'=>['label'=>'Tanggal mulai','type'=>'date','rules'=>'nullable|date'], 'end_date'=>['label'=>'Tanggal selesai','type'=>'date','rules'=>'nullable|date|after_or_equal:start_date'], 'status'=>['label'=>'Status','type'=>'select','options'=>['draft'=>'Draf','published'=>'Terbit','archived'=>'Arsip'],'rules'=>'required|in:draft,published,archived'], 'published_at'=>['label'=>'Waktu terbit','type'=>'datetime-local','rules'=>'nullable|date'],
    ]],
    'profiles' => ['model'=>VillageProfileSection::class,'title'=>'Profil Desa','ability'=>'manage-content','search'=>['title','section_key'],'columns'=>['title'=>'Bagian','section_key'=>'Kunci','status'=>'Status','display_order'=>'Urutan'],'fields'=>['section_key'=>['label'=>'Kunci bagian','rules'=>'required|string|max:50|unique:village_profile_sections,section_key,{id}'],'title'=>['label'=>'Judul','rules'=>'required|string|max:255'],'content'=>['label'=>'Konten','type'=>'editor','rules'=>'required|string|max:100000'],'image_id'=>['label'=>'Gambar bagian','type'=>'image','relation'=>'image','media_category'=>'banners','rules'=>'nullable|exists:media,id'],'status'=>['label'=>'Status','type'=>'select','options'=>['draft'=>'Draf','published'=>'Terbit','archived'=>'Arsip'],'rules'=>'required|in:draft,published,archived'],'display_order'=>['label'=>'Urutan','type'=>'number','rules'=>'required|integer|min:0']]],
    'officials' => ['model'=>Official::class,'title'=>'Perangkat Desa','ability'=>'manage-content','search'=>['name','position'],'columns'=>['name'=>'Nama','position'=>'Jabatan','is_active'=>'Aktif','display_order'=>'Urutan'],'fields'=>['name'=>['label'=>'Nama','rules'=>'required|string|max:255'],'position'=>['label'=>'Jabatan','rules'=>'required|string|max:255'],'photo_id'=>['label'=>'Foto perangkat desa','type'=>'image','relation'=>'photo','media_category'=>'officials','rules'=>'nullable|exists:media,id'],'biography'=>['label'=>'Biografi','type'=>'textarea','rules'=>'nullable|string|max:5000'],'display_order'=>['label'=>'Urutan','type'=>'number','rules'=>'required|integer|min:0'],'is_active'=>['label'=>'Aktif','type'=>'toggle','rules'=>'boolean']]],
    'galleries' => ['model'=>Gallery::class,'title'=>'Galeri','ability'=>'manage-content','search'=>['title','slug'],'columns'=>['title'=>'Judul','status'=>'Status','event_date'=>'Tanggal kegiatan'],'fields'=>['title'=>['label'=>'Judul','rules'=>'required|string|max:255'],'slug'=>['label'=>'Slug','rules'=>'nullable|string|max:255|unique:galleries,slug,{id}'],'description'=>['label'=>'Deskripsi','type'=>'textarea','rules'=>'nullable|string|max:5000'],'event_date'=>['label'=>'Tanggal kegiatan','type'=>'date','rules'=>'nullable|date'],'cover_media_id'=>['label'=>'Gambar sampul','type'=>'image','relation'=>'cover','media_category'=>'gallery','rules'=>'nullable|exists:media,id'],'status'=>['label'=>'Status','type'=>'select','options'=>['draft'=>'Draf','published'=>'Terbit','archived'=>'Arsip'],'rules'=>'required|in:draft,published,archived']]],
    'statistics' => ['model'=>StatisticDataset::class,'title'=>'Dataset Statistik','ability'=>'manage-data','search'=>['title','category','year'],'columns'=>['title'=>'Judul','category'=>'Kategori','year'=>'Tahun','status'=>'Status'],'fields'=>['category'=>['label'=>'Kategori','rules'=>'required|string|max:50'],'title'=>['label'=>'Judul','rules'=>'required|string|max:255'],'slug'=>['label'=>'Slug','rules'=>'nullable|string|max:255|unique:statistic_datasets,slug,{id}'],'description'=>['label'=>'Deskripsi','type'=>'textarea','rules'=>'nullable|string|max:5000'],'year'=>['label'=>'Tahun','type'=>'number','rules'=>'required|integer|min:1900|max:2100'],'unit'=>['label'=>'Satuan','rules'=>'required|string|max:50'],'visualization_type'=>['label'=>'Visualisasi','type'=>'select','options'=>['bar'=>'Batang','line'=>'Garis','pie'=>'Lingkaran','number'=>'Angka'],'rules'=>'required|in:bar,line,pie,number'],'source'=>['label'=>'Sumber','rules'=>'nullable|string|max:255'],'status'=>['label'=>'Status','type'=>'select','options'=>['draft'=>'Draf','published'=>'Terbit','archived'=>'Arsip'],'rules'=>'required|in:draft,published,archived'],'display_order'=>['label'=>'Urutan','type'=>'number','rules'=>'required|integer|min:0']]],
    'idm' => ['model'=>IdmScore::class,'title'=>'Indeks Desa Membangun','ability'=>'manage-data','search'=>['year','status_label'],'columns'=>['year'=>'Tahun','idm_score'=>'IDM','status_label'=>'Status'],'fields'=>['year'=>['label'=>'Tahun','type'=>'number','rules'=>'required|integer|min:1900|max:2100|unique:idm_scores,year,{id}'],'idm_score'=>['label'=>'Skor IDM','type'=>'number','step'=>'0.0001','rules'=>'required|numeric'],'iks_score'=>['label'=>'Skor IKS','type'=>'number','step'=>'0.0001','rules'=>'required|numeric'],'ike_score'=>['label'=>'Skor IKE','type'=>'number','step'=>'0.0001','rules'=>'required|numeric'],'ikl_score'=>['label'=>'Skor IKL','type'=>'number','step'=>'0.0001','rules'=>'required|numeric'],'status_label'=>['label'=>'Status','rules'=>'required|string|max:100'],'source'=>['label'=>'Sumber','rules'=>'nullable|string|max:255']]],
    'map-layers' => ['model'=>MapLayer::class,'title'=>'Layer Peta','ability'=>'manage-data','search'=>['name','slug'],'columns'=>['name'=>'Nama','geometry_type'=>'Geometri','is_visible'=>'Tampil'],'fields'=>['name'=>['label'=>'Nama','rules'=>'required|string|max:255'],'slug'=>['label'=>'Slug','rules'=>'nullable|string|max:255|unique:map_layers,slug,{id}'],'description'=>['label'=>'Deskripsi','type'=>'textarea','rules'=>'nullable|string|max:5000'],'geometry_type'=>['label'=>'Tipe geometri','type'=>'select','options'=>['Point'=>'Titik','LineString'=>'Garis','Polygon'=>'Poligon','Mixed'=>'Campuran'],'rules'=>'required|in:Point,LineString,Polygon,Mixed'],'style_json'=>['label'=>'Style JSON','type'=>'textarea','rules'=>'nullable|json'],'display_order'=>['label'=>'Urutan','type'=>'number','rules'=>'required|integer|min:0'],'is_visible'=>['label'=>'Ditampilkan','type'=>'toggle','rules'=>'boolean']]],
    'map-features' => ['model'=>MapFeature::class,'title'=>'Fitur Peta','ability'=>'manage-data','search'=>['name'],'columns'=>['name'=>'Nama','layer_id'=>'Layer','is_visible'=>'Tampil'],'fields'=>['layer_id'=>['label'=>'Layer','type'=>'relation','model'=>MapLayer::class,'display'=>'name','rules'=>'required|exists:map_layers,id'],'name'=>['label'=>'Nama','rules'=>'required|string|max:255'],'description'=>['label'=>'Deskripsi','type'=>'textarea','rules'=>'nullable|string|max:5000'],'geometry_json'=>['label'=>'GeoJSON geometry','type'=>'textarea','rules'=>'required|json'],'latitude'=>['label'=>'Latitude','type'=>'number','step'=>'0.0000001','rules'=>'nullable|numeric|between:-90,90'],'longitude'=>['label'=>'Longitude','type'=>'number','step'=>'0.0000001','rules'=>'nullable|numeric|between:-180,180'],'photo_id'=>['label'=>'Foto fitur peta','type'=>'image','relation'=>'photo','media_category'=>'map','rules'=>'nullable|exists:media,id'],'properties_json'=>['label'=>'Properti JSON','type'=>'textarea','rules'=>'nullable|json'],'is_visible'=>['label'=>'Ditampilkan','type'=>'toggle','rules'=>'boolean']]],
    'settings' => ['model'=>Setting::class,'title'=>'Pengaturan Situs','ability'=>'manage-users','search'=>['key','group'],'columns'=>['key'=>'Kunci','group'=>'Grup','value'=>'Nilai','is_public'=>'Publik'],'fields'=>['key'=>['label'=>'Kunci','rules'=>'required|string|max:100|unique:settings,key,{id}'],'value'=>['label'=>'Nilai','type'=>'textarea','rules'=>'nullable|string|max:10000'],'type'=>['label'=>'Tipe','type'=>'select','options'=>['string'=>'Teks','text'=>'Teks panjang','boolean'=>'Boolean','integer'=>'Angka'],'rules'=>'required|in:string,text,boolean,integer'],'group'=>['label'=>'Grup','rules'=>'required|string|max:50'],'is_public'=>['label'=>'Publik','type'=>'toggle','rules'=>'boolean']]],
    'redirects' => ['model'=>Redirect::class,'title'=>'Redirect URL','ability'=>'manage-users','search'=>['old_path','new_path'],'columns'=>['old_path'=>'Path lama','new_path'=>'Tujuan','status_code'=>'Kode'],'fields'=>['old_path'=>['label'=>'Path lama','rules'=>'required|string|max:500|starts_with:/|unique:redirects,old_path,{id}'],'new_path'=>['label'=>'Path tujuan','rules'=>'required|string|max:500|starts_with:/|different:old_path'],'status_code'=>['label'=>'Kode HTTP','type'=>'select','options'=>['301'=>'301 permanen','302'=>'302 sementara'],'rules'=>'required|in:301,302']]],
    'publication-attachments' => ['model'=>PublicationAttachment::class,'title'=>'Lampiran Publikasi','ability'=>'manage-content','search'=>['title'],'columns'=>['publication_id'=>'Publikasi','media_id'=>'Media','title'=>'Judul','display_order'=>'Urutan'],'fields'=>['publication_id'=>['label'=>'Publikasi','type'=>'relation','model'=>Publication::class,'display'=>'title','rules'=>'required|exists:publications,id'],'media_id'=>['label'=>'Media','type'=>'relation','model'=>Media::class,'display'=>'original_name','rules'=>'required|exists:media,id'],'title'=>['label'=>'Judul tampilan','rules'=>'nullable|string|max:255'],'display_order'=>['label'=>'Urutan','type'=>'number','rules'=>'required|integer|min:0']]],
    'statistic-values' => ['model'=>StatisticValue::class,'title'=>'Nilai Statistik','ability'=>'manage-data','search'=>['label'],'columns'=>['dataset_id'=>'Dataset','label'=>'Label','value'=>'Nilai','display_order'=>'Urutan'],'fields'=>['dataset_id'=>['label'=>'Dataset','type'=>'relation','model'=>StatisticDataset::class,'display'=>'title','rules'=>'required|exists:statistic_datasets,id'],'label'=>['label'=>'Label','rules'=>'required|string|max:255'],'value'=>['label'=>'Nilai','type'=>'number','step'=>'0.0001','rules'=>'required|numeric'],'secondary_value'=>['label'=>'Nilai tambahan','type'=>'number','step'=>'0.0001','rules'=>'nullable|numeric'],'display_order'=>['label'=>'Urutan','type'=>'number','rules'=>'required|integer|min:0'],'metadata_json'=>['label'=>'Metadata JSON','type'=>'textarea','rules'=>'nullable|json']]],
    'gallery-items' => ['model'=>GalleryItem::class,'title'=>'Item Galeri','ability'=>'manage-content','search'=>['caption'],'columns'=>['gallery_id'=>'Galeri','media_id'=>'Media','caption'=>'Keterangan','display_order'=>'Urutan'],'fields'=>['gallery_id'=>['label'=>'Galeri','type'=>'relation','model'=>Gallery::class,'display'=>'title','rules'=>'required|exists:galleries,id'],'media_id'=>['label'=>'Gambar','type'=>'image','relation'=>'media','media_category'=>'gallery','rules'=>'required|exists:media,id'],'caption'=>['label'=>'Keterangan','type'=>'textarea','rules'=>'nullable|string|max:2000'],'display_order'=>['label'=>'Urutan','type'=>'number','rules'=>'required|integer|min:0']]],
]];
