<?php

return [
    'population_menus' => [
        'agama' => 'population-religion',
        'akte-kelahiran' => 'population-birth-certificate',
        'akseptor-kb' => 'population-family-planning',
        'penyandang-cacat' => 'population-disability',
        'golongan-darah' => 'population-blood-type',
        'status-penduduk' => 'population-residency-status',
        'status-perkawinan' => 'population-marital-status',
        'rentang-umur' => 'age-range',
        'kategori-umur' => 'age-categories',
        'wajib-ktp' => 'population-id-card',
        'warga-negara' => 'population-citizenship',
    ],

    'section_contexts' => [
        'keluarga' => [
            '' => 'family-summary',
            'kepala-keluarga' => 'family-heads',
            'anggota-keluarga' => 'family-members',
            'rumah-tangga' => 'households',
        ],
        'pendidikan' => ['' => 'education-family'],
        'pekerjaan' => ['' => 'occupation'],
        'ekonomi' => ['' => 'economy'],
        'idm' => ['' => 'idm'],
        'visualisasi' => ['' => 'visualization'],
    ],

    'contexts' => [
        'population-religion' => [
            'title' => 'Statistik Agama',
            'description' => 'Komposisi penduduk Desa Sukomulyo berdasarkan agama yang tercatat.',
            'unit' => 'jiwa',
            'chart' => 'pie',
            'values' => [
                ['Islam', 45, 2],
                ['Kristen', 4, 0],
                ['Katolik', 2, 0],
                ['Hindu', 1, 0],
            ],
        ],
        'population-birth-certificate' => [
            'title' => 'Statistik Akta Kelahiran',
            'description' => 'Kepemilikan akta kelahiran penduduk yang tercatat dalam administrasi desa.',
            'unit' => 'jiwa',
            'chart' => 'pie',
            'values' => [
                ['Memiliki Akta', 43, 3],
                ['Belum Memiliki', 9, -1],
            ],
        ],
        'population-family-planning' => [
            'title' => 'Statistik Akseptor KB',
            'description' => 'Sebaran peserta keluarga berencana berdasarkan metode kontrasepsi.',
            'unit' => 'akseptor',
            'chart' => 'pie',
            'values' => [
                ['Suntik', 8, 1],
                ['Pil', 6, 1],
                ['IUD', 3, 0],
                ['Implan', 2, 0],
                ['Lainnya', 1, 0],
            ],
        ],
        'population-disability' => [
            'title' => 'Statistik Penyandang Disabilitas',
            'description' => 'Data penduduk penyandang disabilitas berdasarkan ragam kebutuhan dukungan.',
            'unit' => 'jiwa',
            'chart' => 'bar',
            'values' => [
                ['Fisik', 2, 0],
                ['Sensorik', 1, 0],
                ['Intelektual', 1, 0],
                ['Mental', 1, 0],
            ],
        ],
        'population-blood-type' => [
            'title' => 'Statistik Golongan Darah',
            'description' => 'Komposisi golongan darah penduduk yang telah tercatat.',
            'unit' => 'jiwa',
            'chart' => 'pie',
            'values' => [
                ['A', 12, 1],
                ['B', 10, 1],
                ['AB', 5, 0],
                ['O', 18, 1],
                ['Belum Terdata', 7, -1],
            ],
        ],
        'population-residency-status' => [
            'title' => 'Statistik Status Penduduk',
            'description' => 'Komposisi penduduk berdasarkan status domisili administrasi.',
            'unit' => 'jiwa',
            'chart' => 'pie',
            'values' => [
                ['Penduduk Tetap', 48, 2],
                ['Penduduk Sementara', 3, 0],
                ['Pendatang', 1, 0],
            ],
        ],
        'population-marital-status' => [
            'title' => 'Statistik Status Perkawinan',
            'description' => 'Komposisi penduduk berdasarkan status perkawinan.',
            'unit' => 'jiwa',
            'chart' => 'pie',
            'values' => [
                ['Belum Kawin', 18, 1],
                ['Kawin', 29, 1],
                ['Cerai Hidup', 2, 0],
                ['Cerai Mati', 3, 0],
            ],
        ],
        'age-range' => [
            'title' => 'Statistik Rentang Umur',
            'description' => 'Sebaran penduduk berdasarkan rentang umur yang dapat dipilih pada grafik tahunan.',
            'unit' => 'jiwa',
            'chart' => 'bar',
            'values' => [
                ['0–4 tahun', 5, 1],
                ['5–14 tahun', 12, 1],
                ['15–24 tahun', 10, 1],
                ['25–44 tahun', 15, 1],
                ['45–64 tahun', 10, 0],
                ['65+ tahun', 7, 0],
            ],
        ],
        'age-categories' => [
            'title' => 'Statistik Kategori Umur',
            'description' => 'Komposisi seluruh penduduk berdasarkan kategori kelompok umur.',
            'unit' => 'jiwa',
            'chart' => 'bar',
            'values' => [
                ['Balita', 5, 1],
                ['Anak', 12, 1],
                ['Remaja', 8, 0],
                ['Dewasa', 20, 0],
                ['Lansia', 7, 0],
            ],
        ],
        'population-id-card' => [
            'title' => 'Statistik Kepemilikan Wajib KTP',
            'description' => 'Status kepemilikan KTP bagi penduduk wajib KTP.',
            'unit' => 'jiwa',
            'chart' => 'pie',
            'values' => [
                ['Wajib KTP dan Memiliki', 34, 2],
                ['Wajib KTP Belum Memiliki', 4, 0],
                ['Belum Wajib KTP', 14, 0],
            ],
        ],
        'population-citizenship' => [
            'title' => 'Statistik Warga Negara',
            'description' => 'Komposisi penduduk berdasarkan status kewarganegaraan.',
            'unit' => 'jiwa',
            'chart' => 'pie',
            'values' => [
                ['WNI', 51, 2],
                ['WNA', 1, 0],
            ],
        ],
        'education-family' => [
            'title' => 'Statistik Pendidikan',
            'description' => 'Sebaran jenjang pendidikan penduduk Desa Sukomulyo dalam satu halaman statistik.',
            'unit' => 'jiwa',
            'chart' => 'bar',
            'values' => [
                ['Tidak/Belum Sekolah', 7, 0],
                ['SD/Sederajat', 14, 1],
                ['SMP/Sederajat', 11, 0],
                ['SMA/Sederajat', 14, 1],
                ['Diploma/Sarjana', 6, 0],
            ],
        ],
        'occupation' => [
            'title' => 'Statistik Pekerjaan',
            'description' => 'Sebaran pekerjaan dan mata pencaharian penduduk Desa Sukomulyo.',
            'unit' => 'jiwa',
            'chart' => 'bar',
            'values' => [
                ['Petani/Pekebun', 15, 1],
                ['Wiraswasta', 9, 1],
                ['Pelajar/Mahasiswa', 11, 0],
                ['Mengurus Rumah Tangga', 8, 0],
                ['Karyawan', 5, 0],
                ['Buruh Harian Lepas', 4, 1],
                ['ASN/TNI/Polri', 2, 0],
                ['Perangkat Desa', 2, 0],
                ['Belum/Tidak Bekerja', 5, 0],
                ['Lainnya', 3, 0],
            ],
        ],
        'family-summary' => [
            'title' => 'Statistik Keluarga',
            'description' => 'Ringkasan perkembangan keluarga, rumah tangga, penduduk, dan wilayah desa.',
            'unit' => 'data',
            'chart' => 'bar',
            'values' => [
                ['Keluarga', 16, 1, 'KK'],
                ['Penduduk', 52, 2, 'jiwa'],
                ['Rumah Tangga', 15, 1, 'rumah tangga'],
                ['Wilayah Dusun', 3, 0, 'dusun'],
            ],
        ],
        'family-heads' => [
            'title' => 'Statistik Kepala Keluarga',
            'description' => 'Komposisi kepala keluarga berdasarkan jenis kelamin.',
            'unit' => 'KK',
            'chart' => 'pie',
            'values' => [
                ['Laki-laki', 14, 1],
                ['Perempuan', 2, 0],
            ],
        ],
        'family-members' => [
            'title' => 'Statistik Anggota Keluarga',
            'description' => 'Sebaran keluarga berdasarkan jumlah anggota dalam satu kartu keluarga.',
            'unit' => 'KK',
            'chart' => 'bar',
            'values' => [
                ['1–2 anggota', 3, 0],
                ['3–4 anggota', 8, 1],
                ['5–6 anggota', 4, 0],
                ['Lebih dari 6', 1, 0],
            ],
        ],
        'households' => [
            'title' => 'Statistik Rumah Tangga',
            'description' => 'Komposisi rumah tangga berdasarkan status hunian.',
            'unit' => 'rumah tangga',
            'chart' => 'pie',
            'values' => [
                ['Milik Sendiri', 11, 1],
                ['Sewa/Kontrak', 2, 0],
                ['Menumpang', 1, 0],
                ['Lainnya', 1, 0],
            ],
        ],
        'economy' => [
            'title' => 'Statistik Ekonomi',
            'description' => 'Perkembangan unit aktivitas ekonomi masyarakat menurut sektor.',
            'unit' => 'unit usaha',
            'chart' => 'bar',
            'values' => [
                ['Pertanian', 15, 1],
                ['Perdagangan', 8, 1],
                ['UMKM Olahan', 6, 1],
                ['Jasa', 5, 1],
                ['Peternakan', 4, 0],
            ],
        ],
        'idm' => [
            'title' => 'IDM (Indeks Desa Membangun)',
            'trend_title' => 'IDM',
            'description' => 'Perkembangan Indeks Ketahanan Sosial, Ekonomi, Lingkungan, dan nilai IDM desa.',
            'unit' => 'indeks',
            'chart' => 'bar',
            'decimals' => 4,
            'show_total' => false,
            'values' => [
                ['IDM', 0.6900, 0.0150],
                ['IKS', 0.7100, 0.0125],
                ['IKE', 0.6600, 0.0175],
                ['IKL', 0.7000, 0.0150],
            ],
        ],
        'visualization' => [
            'title' => 'Visualisasi Data Desa',
            'trend_title' => 'Indikator Desa',
            'description' => 'Ringkasan indikator utama Desa Sukomulyo dalam grafik dan tabel lima tahunan.',
            'unit' => 'data',
            'chart' => 'bar',
            'values' => [
                ['Penduduk', 52, 2, 'jiwa'],
                ['Keluarga', 16, 1, 'KK'],
                ['Rumah Tangga', 15, 1, 'rumah tangga'],
                ['Unit Usaha', 38, 4, 'unit usaha'],
            ],
        ],
    ],
];
