@extends('layouts.admin')
@section('title', ($item->exists ? 'Ubah ' : 'Tambah ').$config['title'])
@section('page-description', $item->exists ? 'Perbarui informasi publik desa' : 'Tambahkan informasi publik baru')
@section('content')
@php
    $isVillageRegulation = ($config['publication_type'] ?? null) === 'regulation';
    $selectedMediaId = old('featured_image_id', $item->featured_image_id);
    $selectedMedia = ($media ?? collect())->firstWhere('id', (int) $selectedMediaId) ?? $item->featuredImage;
@endphp
<form method="post" enctype="multipart/form-data" action="{{ $item->exists ? route('admin.resources.update', ['publications', $item]) : route('admin.resources.store', 'publications') }}" data-dirty-form id="publication-form">
@csrf @if($item->exists) @method('put') @endif
@if($isVillageRegulation)<input type="hidden" name="type" value="regulation">@endif
<div class="row"><div class="col-md-8">
    <div class="box box-info"><div class="box-header with-border">
        <a class="btn btn-info btn-sm" href="{{ route('admin.resources.index', array_filter(['resource' => 'publications', 'type' => request('type', $item->type)])) }}"><i class="fa fa-arrow-left"></i> Kembali ke Daftar</a>
        @if($item->exists && $item->type === 'announcement' && $item->status === 'published')<a class="btn btn-success btn-sm" target="_blank" href="{{ route('announcements.show', $item->slug) }}"><i class="fa fa-eye"></i> Lihat Pengumuman</a>@endif
    </div><div class="box-body">
        @unless($isVillageRegulation)
        <div class="form-group {{ $errors->has('type') ? 'has-error' : '' }}"><label class="required" for="type">Jenis Informasi</label><select class="form-control select2" required id="type" name="type">@foreach($config['fields']['type']['options'] as $value => $label)<option value="{{ $value }}" @selected(old('type', request('type', $item->type)) === $value)>{{ $label }}</option>@endforeach</select>@error('type')<span class="field-error">{{ $message }}</span>@enderror</div>
        @endunless
        <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}"><label class="required" for="title">Judul Informasi</label><input id="title" name="title" class="form-control input-lg" maxlength="255" required value="{{ old('title', $item->title) }}" placeholder="Masukkan judul informasi"><span class="help-block">Maksimal 255 karakter.</span>@error('title')<span class="field-error">{{ $message }}</span>@enderror</div>
        @unless($isVillageRegulation)
        <div class="form-group {{ $errors->has('content') ? 'has-error' : '' }}"><label class="required">Isi Informasi</label><x-admin.rich-editor name="content" :value="old('content', $item->content)" placeholder="Tulis isi informasi publik di sini..." />@error('content')<span class="field-error">{{ $message }}</span>@enderror</div>
        <div class="form-group {{ $errors->has('excerpt') ? 'has-error' : '' }}"><label for="excerpt">Ringkasan Informasi</label><textarea class="form-control" rows="4" maxlength="1000" id="excerpt" name="excerpt" placeholder="Ringkasan singkat yang tampil pada daftar informasi">{{ old('excerpt', $item->excerpt) }}</textarea><span class="help-block">Jika dikosongkan, cuplikan akan diambil dari isi informasi.</span>@error('excerpt')<span class="field-error">{{ $message }}</span>@enderror</div>
        @endunless
        <div class="publication-attachment-manager" @if(!$isVillageRegulation) data-publication-attachments @endif>
            <hr><h4><i class="fa fa-file-pdf-o text-red"></i> Lampiran PDF</h4>
            <p class="help-block">{{ $isVillageRegulation ? 'Unggah satu file PDF maksimal 10 MB. File baru akan menggantikan lampiran lama.' : 'Unggah maksimal 10 PDF per sekali simpan, masing-masing maksimal 10 MB. Lampiran pertama menjadi PDF utama.' }}</p>
            <div class="form-group {{ $errors->has('attachment_uploads.*') ? 'has-error' : '' }}"><label for="attachment_uploads">{{ $isVillageRegulation && $item->exists ? 'Ganti lampiran PDF' : 'Tambah lampiran PDF' }}</label><input id="attachment_uploads" type="file" name="attachment_uploads[]" class="form-control" accept="application/pdf,.pdf" @if(!$isVillageRegulation) multiple data-attachment-files @elseif(!$item->exists || $publicationAttachments->isEmpty()) required @endif>@error('attachment_uploads')<span class="field-error"><i class="fa fa-times-circle-o"></i> {{ $message }}</span>@enderror @error('attachment_uploads.*')<span class="field-error"><i class="fa fa-times-circle-o"></i> {{ $message }}</span>@enderror</div>
            <div class="publication-attachment-list" data-attachment-list>
                @if($isVillageRegulation)
                    @foreach($publicationAttachments->take(1) as $attachment)<div class="publication-attachment-row"><i class="fa fa-file-pdf-o text-red publication-attachment-file-icon"></i><div class="publication-attachment-fields"><strong>{{ $attachment->media?->original_name }}</strong></div></div>@endforeach
                @else
                    @foreach($publicationAttachments as $attachment)<div class="publication-attachment-row" data-attachment-row data-existing-attachment><span class="publication-attachment-handle" title="Urutkan lampiran"><i class="fa fa-bars"></i></span><i class="fa fa-file-pdf-o text-red publication-attachment-file-icon"></i><div class="publication-attachment-fields"><strong>{{ $attachment->media?->original_name }}</strong><input type="text" name="publication_attachments[{{ $attachment->id }}][title]" class="form-control input-sm" value="{{ old('publication_attachments.'.$attachment->id.'.title', $attachment->title) }}" placeholder="Judul tampilan (opsional)"><input type="hidden" name="publication_attachments[{{ $attachment->id }}][display_order]" value="{{ $attachment->display_order }}" data-attachment-order><input type="hidden" name="attachment_sequence[]" value="existing:{{ $attachment->id }}" data-attachment-sequence><label class="publication-attachment-remove"><input type="checkbox" name="remove_publication_attachments[]" value="{{ $attachment->id }}" data-attachment-remove> Hapus lampiran</label></div><div class="publication-attachment-controls"><button type="button" class="btn btn-default btn-xs" data-attachment-up aria-label="Naikkan urutan"><i class="fa fa-arrow-up"></i></button><button type="button" class="btn btn-default btn-xs" data-attachment-down aria-label="Turunkan urutan"><i class="fa fa-arrow-down"></i></button></div></div>@endforeach
                @endif
            </div>
        </div>
    </div></div>
</div><div class="col-md-4">
    @unless($isVillageRegulation)
    <div class="box box-info"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-image"></i> Gambar Utama</h3></div><div class="box-body"><x-admin.image-picker name="featured_image_id" label="Gambar Utama" :media="$media" :selected="$selectedMedia" :show-label="false" /></div></div>
    <div class="box box-info"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-send"></i> Publikasi</h3></div><div class="box-body"><div class="form-group {{ $errors->has('status') ? 'has-error' : '' }}"><label class="required" for="status">Status</label><select class="form-control select2" id="status" name="status">@foreach($config['fields']['status']['options'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $item->status ?: 'draft') === $value)>{{ $label }}</option>@endforeach</select>@error('status')<span class="field-error">{{ $message }}</span>@enderror</div><div class="form-group {{ $errors->has('published_at') ? 'has-error' : '' }}"><label for="published_at">Tanggal Posting</label><div class="input-group"><span class="input-group-addon"><i class="fa fa-calendar"></i></span><input class="form-control" type="datetime-local" id="published_at" name="published_at" value="{{ old('published_at', $item->published_at?->format('Y-m-d\\TH:i')) }}"></div><span class="help-block">Wajib diisi saat status Terbit.</span>@error('published_at')<span class="field-error">{{ $message }}</span>@enderror</div></div></div>
    <div class="box box-info"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-calendar"></i> Jadwal Informasi</h3></div><div class="box-body"><div class="form-group"><label for="start_date">Tanggal Mulai</label><input class="form-control" type="date" id="start_date" name="start_date" value="{{ old('start_date', $item->start_date?->format('Y-m-d')) }}">@error('start_date')<span class="field-error">{{ $message }}</span>@enderror</div><div class="form-group"><label for="end_date">Tanggal Selesai</label><input class="form-control" type="date" id="end_date" name="end_date" value="{{ old('end_date', $item->end_date?->format('Y-m-d')) }}">@error('end_date')<span class="field-error">{{ $message }}</span>@enderror</div></div></div>
    <div class="box box-info collapsed-box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-tags"></i> Kata Kunci</h3><div class="box-tools"><button type="button" class="btn btn-box-tool" data-widget="collapse" aria-label="Buka atau tutup kata kunci"><i class="fa fa-plus"></i></button></div></div><div class="box-body"><div class="form-group {{ $errors->has('seo_keywords') ? 'has-error' : '' }}"><label for="seo_keywords">Kata Kunci Informasi</label><input class="form-control" id="seo_keywords" name="seo_keywords" maxlength="500" value="{{ old('seo_keywords', $item->seo_keywords) }}" placeholder="Contoh: pengumuman desa, pelayanan, Sukomulyo"><span class="help-block">Pisahkan setiap kata kunci dengan koma. Judul dan deskripsi mesin pencari otomatis menggunakan judul serta ringkasan informasi.</span>@error('seo_keywords')<span class="field-error">{{ $message }}</span>@enderror</div></div></div>
    @endunless
    <button type="submit" class="btn btn-social btn-info btn-block"><i class="fa fa-save"></i> Simpan {{ $config['title'] }}</button>
</div></div></form>
@endsection
