@extends('layouts.admin')
@section('title',($item->exists?'Ubah':'Tambah').' Artikel')
@section('page-description',$item->exists?'Perbarui berita desa':'Tulis berita baru')
@section('content')
<form method="post" enctype="multipart/form-data" action="{{ $item->exists?route('admin.resources.update',['news',$item]):route('admin.resources.store','news') }}" data-dirty-form id="news-form">@csrf @if($item->exists)@method('put')@endif
<div class="row"><div class="col-md-8">
    <div class="box box-info"><div class="box-header with-border"><a class="btn btn-info btn-sm" href="{{ route('admin.resources.index','news') }}"><i class="fa fa-arrow-left"></i> Kembali ke Daftar Artikel</a>@if($item->exists && $item->slug)<a class="btn btn-success btn-sm" target="_blank" href="{{ route('berita-desa.show',$item->slug) }}"><i class="fa fa-eye"></i> Lihat Artikel</a>@endif</div>
    <div class="box-body">
        <div class="form-group {{ $errors->has('title')?'has-error':'' }}"><label class="required" for="title">Judul Artikel</label><input id="title" name="title" class="form-control input-lg" minlength="5" maxlength="255" required value="{{ old('title',$item->title) }}" placeholder="Masukkan judul artikel"><span class="help-block">Judul artikel minimal 5 karakter dan maksimal 255 karakter. <span class="pull-right"><b id="title-count">0</b>/255</span></span>@error('title')<span class="field-error">{{ $message }}</span>@enderror</div>
        <div class="form-group {{ $errors->has('content')?'has-error':'' }}"><label class="required">Isi Artikel</label><div class="article-editor" data-article-editor><div class="article-editor-toolbar" role="toolbar"><button type="button" data-command="undo" title="Urungkan"><i class="fa fa-undo"></i></button><button type="button" data-command="redo" title="Ulangi"><i class="fa fa-repeat"></i></button><span></span><button type="button" data-command="bold"><i class="fa fa-bold"></i></button><button type="button" data-command="italic"><i class="fa fa-italic"></i></button><button type="button" data-command="underline"><i class="fa fa-underline"></i></button><span></span><button type="button" data-command="formatBlock" data-value="h2">H2</button><button type="button" data-command="formatBlock" data-value="h3">H3</button><button type="button" data-command="formatBlock" data-value="p">P</button><span></span><button type="button" data-command="insertUnorderedList"><i class="fa fa-list-ul"></i></button><button type="button" data-command="insertOrderedList"><i class="fa fa-list-ol"></i></button><button type="button" data-command="formatBlock" data-value="blockquote"><i class="fa fa-quote-right"></i></button><span></span><button type="button" data-action="link"><i class="fa fa-link"></i></button><button type="button" data-command="removeFormat"><i class="fa fa-eraser"></i></button></div><div class="article-editor-surface" contenteditable="true" data-placeholder="Mulai tulis isi berita di sini...">{!! old('content',$item->content) !!}</div><textarea hidden name="content" id="content">{{ old('content',$item->content) }}</textarea></div>@error('content')<span class="field-error">{{ $message }}</span>@enderror</div>
        <div class="form-group"><label for="excerpt">Ringkasan Artikel</label><textarea class="form-control" rows="4" maxlength="1000" id="excerpt" name="excerpt" placeholder="Ringkasan singkat yang tampil pada daftar berita">{{ old('excerpt',$item->excerpt) }}</textarea><span class="help-block">Jika dikosongkan, cuplikan akan diambil dari isi artikel.</span></div>
    </div></div>
</div><div class="col-md-4">
    <div class="box box-info"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-send"></i> Publikasi</h3></div><div class="box-body">
        <div class="form-group"><label class="required" for="status">Status Artikel</label><select class="form-control select2" id="status" name="status">@foreach(['draft'=>'Draf','published'=>'Terbit','archived'=>'Arsip'] as $value=>$label)<option value="{{ $value }}" @selected(old('status',$item->status ?: 'draft')===$value)>{{ $label }}</option>@endforeach</select></div>
        <div class="form-group"><label for="published_at">Tanggal Posting</label><div class="input-group"><span class="input-group-addon"><i class="fa fa-calendar"></i></span><input class="form-control" type="datetime-local" id="published_at" name="published_at" value="{{ old('published_at',$item->published_at?->format('Y-m-d\TH:i')) }}"></div><span class="help-block">Kosongkan untuk memakai waktu publikasi saat ini.</span></div>
    </div><div class="box-footer"><button type="submit" class="btn btn-social btn-info btn-block"><i class="fa fa-save"></i> Simpan Artikel</button></div></div>
    <div class="box box-info"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-folder-open"></i> Kategori & URL</h3></div><div class="box-body"><div class="form-group"><label class="required" for="category_id">Kategori</label><select class="form-control select2" required id="category_id" name="category_id"><option value="">-- Pilih kategori --</option>@foreach($relations['category_id'] as $category)<option value="{{ $category->id }}" @selected((string)old('category_id',$item->category_id)===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="form-group"><label for="slug">Slug / alamat URL</label><input class="form-control" id="slug" name="slug" maxlength="255" value="{{ old('slug',$item->slug) }}" placeholder="dibuat-otomatis-dari-judul"><span class="help-block">Boleh dikosongkan agar dibuat otomatis.</span></div></div></div>
    <div class="box box-info"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-image"></i> Gambar Utama</h3></div><div class="box-body"><div class="featured-preview" id="featured-preview">@if($item->featuredImage)<img src="{{ $item->featuredImage->url }}" alt="">@else<i class="fa fa-picture-o"></i><span>Belum ada gambar</span>@endif</div><div class="form-group"><label for="featured_image_upload">Unggah gambar baru</label><input type="file" id="featured_image_upload" name="featured_image_upload" accept="image/jpeg,image/png,image/webp"><span class="help-block">JPG, PNG, atau WEBP. Maksimal 5 MB.</span></div><div class="form-group"><label for="featured_image_id">Atau pilih dari pustaka</label><select class="form-control select2" id="featured_image_id" name="featured_image_id"><option value="">Tanpa gambar</option>@foreach($media as $image)<option value="{{ $image->id }}" data-url="{{ $image->url }}" @selected((string)old('featured_image_id',$item->featured_image_id)===(string)$image->id)>{{ $image->original_name }}</option>@endforeach</select></div><a href="{{ route('admin.media.index') }}" target="_blank" class="btn btn-default btn-sm"><i class="fa fa-folder-open"></i> Buka Pustaka Media</a></div></div>
    <div class="box box-info collapsed-box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-search"></i> Pengaturan SEO</h3><div class="box-tools"><button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button></div></div><div class="box-body"><div class="form-group"><label for="seo_title">Judul SEO</label><input class="form-control" id="seo_title" name="seo_title" maxlength="255" value="{{ old('seo_title',$item->seo_title) }}"></div><div class="form-group"><label for="seo_description">Deskripsi SEO</label><textarea class="form-control" id="seo_description" name="seo_description" maxlength="320" rows="4">{{ old('seo_description',$item->seo_description) }}</textarea></div></div></div>
</div></div></form>
@endsection
