<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Services\{ActivityLogger,HtmlSanitizer,ImageProcessor};
use App\Models\{Media,News};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CrudController extends Controller
{
 public function __construct(private ActivityLogger $logger,private HtmlSanitizer $sanitizer,private ImageProcessor $images){}
 private function resource(string $resource): array { $c=config("admin.resources.$resource"); abort_unless($c,404); return $c; }
 private function ensureResourceAuthorized(array $c): void { abort_unless(auth()->user()->can($c['ability']),403); }
 public function index(Request $r,string $resource){$c=$this->resource($resource);$this->ensureResourceAuthorized($c);$q=$c['model']::query();if($resource==='news'){$q->with(['category','author','featuredImage']);if($status=$r->query('status'))$q->where('status',$status);if($category=$r->query('category'))$q->where('category_id',$category);}if($s=trim((string)$r->query('q'))) $q->where(function($x)use($c,$s){foreach($c['search'] as $i=>$field)$i?$x->orWhere($field,'like',"%$s%"): $x->where($field,'like',"%$s%");});$data=['resource'=>$resource,'config'=>$c,'items'=>$q->latest('id')->paginate(15)->withQueryString()];if($resource==='news')$data['categories']=$this->relations($c)['category_id'];return view($resource==='news'?'admin.news.index':'admin.crud.index',$data);}
 public function create(string $resource){$c=$this->resource($resource);$this->ensureResourceAuthorized($c);return view($resource==='news'?'admin.news.form':'admin.crud.form',$this->formData($resource,$c,new $c['model']));}
 public function store(Request $r,string $resource){$c=$this->resource($resource);$this->ensureResourceAuthorized($c);$data=$this->validated($r,$c);if($resource==='news'){$data=$this->prepareNewsImage($r,$data);if(empty($data['slug']))$data['slug']=$this->uniqueNewsSlug($data['title']);}$item=DB::transaction(function()use($c,$data,$resource){$item=$c['model']::create($this->prepare($data,$c));$this->logger->log('created',$resource,$item,null,$item->toArray());return $item;});return redirect()->route('admin.resources.edit',[$resource,$item])->with('success',$c['title'].' berhasil ditambahkan.');}
 public function edit(string $resource,int $id){$c=$this->resource($resource);$this->ensureResourceAuthorized($c);$item=$c['model']::findOrFail($id);if($resource==='news')$item->load(['featuredImage','category']);return view($resource==='news'?'admin.news.form':'admin.crud.form',$this->formData($resource,$c,$item));}
 public function update(Request $r,string $resource,int $id){$c=$this->resource($resource);$this->ensureResourceAuthorized($c);$item=$c['model']::findOrFail($id);$data=$this->validated($r,$c,$id);if($resource==='news'){$data=$this->prepareNewsImage($r,$data);if(empty($data['slug']))$data['slug']=$item->slug;}DB::transaction(function()use($item,$data,$c,$resource){$old=$item->toArray();$item->update($this->prepare($data,$c));$this->logger->log('updated',$resource,$item,$old,$item->fresh()->toArray());});return back()->with('success',$c['title'].' berhasil diperbarui.');}
 public function destroy(string $resource,int $id){$c=$this->resource($resource);$this->ensureResourceAuthorized($c);$item=$c['model']::findOrFail($id);$this->logger->log('deleted',$resource,$item,$item->toArray());$item->delete();return redirect()->route('admin.resources.index',$resource)->with('success','Data berhasil dihapus.');}
 private function validated(Request $r,array $c,?int $id=null): array {$rules=[];foreach($c['fields'] as $key=>$field)$rules[$key]=str_replace('{id}',(string)($id??'NULL'),$field['rules']??'nullable');return $r->validate($rules);}
 private function prepare(array $data,array $c): array {foreach($c['fields'] as $key=>$field){if(($field['type']??'')==='toggle')$data[$key]=(bool)($data[$key]??false);if(($field['type']??'')==='editor')$data[$key]=$this->sanitizer->clean($data[$key]??'');if(str_ends_with($key,'_json')&&isset($data[$key])&&is_string($data[$key]))$data[$key]=json_decode($data[$key],true);}if(array_key_exists('slug',$c['fields'])&&empty($data['slug']))$data['slug']=Str::slug($data['title']??$data['name']);$model=new $c['model'];$columns=$model->getConnection()->getSchemaBuilder()->getColumnListing($model->getTable());foreach(['author_id','created_by','updated_by'] as $key)if(in_array($key,$columns,true))$data[$key]=auth()->id();return $data;}
 private function relations(array $c): array {$out=[];foreach($c['fields'] as $key=>$f)if(($f['type']??'')==='relation')$out[$key]=$f['model']::orderBy($f['display'])->get(['id',$f['display']]);return $out;}
 private function formData(string $resource,array $c,$item): array { $data=['resource'=>$resource,'config'=>$c,'item'=>$item,'relations'=>$this->relations($c)];if($resource==='news')$data['media']=Media::where('mime_type','like','image/%')->latest()->limit(60)->get();return $data; }
 private function prepareNewsImage(Request $r,array $data): array { $extra=$r->validate(['featured_image_upload'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120','featured_image_alt'=>'nullable|string|max:255','remove_featured_image'=>'nullable|boolean']);if($r->boolean('remove_featured_image'))$data['featured_image_id']=null;if($r->hasFile('featured_image_upload')){$file=$r->file('featured_image_upload');$disk=config('filesystems.media_disk','public');$folder=Str::slug($data['slug']??$data['title']??'')?:'berita-baru';$media=Media::create(array_merge($this->images->store($file,'berita/'.$folder,$disk),['original_name'=>$file->getClientOriginalName(),'disk'=>$disk,'alt_text'=>$extra['featured_image_alt']?:($data['title']??null),'uploaded_by'=>auth()->id()]));$data['featured_image_id']=$media->id;}elseif(!empty($data['featured_image_id'])&&array_key_exists('featured_image_alt',$extra)){Media::whereKey($data['featured_image_id'])->update(['alt_text'=>$extra['featured_image_alt']]);}return $data; }
 private function uniqueNewsSlug(string $title): string {$base=Str::slug($title)?:'artikel';$slug=$base;$suffix=2;while(News::withTrashed()->where('slug',$slug)->exists())$slug=$base.'-'.$suffix++;return $slug;}
 public function trash(){ $c=$this->resource('news');$this->ensureResourceAuthorized($c);return view('admin.news.trash',['items'=>News::onlyTrashed()->with(['category','author','featuredImage'])->latest('deleted_at')->paginate(15)]); }
 public function restore(int $id){$c=$this->resource('news');$this->ensureResourceAuthorized($c);$item=News::onlyTrashed()->findOrFail($id);$item->restore();$this->logger->log('restored','news',$item);return back()->with('success','Artikel berhasil dipulihkan.');}
 public function forceDelete(int $id){$c=$this->resource('news');$this->ensureResourceAuthorized($c);$item=News::onlyTrashed()->findOrFail($id);$this->logger->log('force_deleted','news',$item,$item->toArray());$item->forceDelete();return back()->with('success','Artikel dihapus permanen.');}
 public function emptyTrash(){ $c=$this->resource('news');$this->ensureResourceAuthorized($c);News::onlyTrashed()->get()->each(function(News $item){$this->logger->log('force_deleted','news',$item,$item->toArray());$item->forceDelete();});return back()->with('success','Tempat sampah dikosongkan.');}
}
